spring:
  application:
    name: auth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 29732969735-cdjicbu05u9qopg5msbllcqte7u08peq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          github:
            client-id: Ov23lip0EUwRn7f9RjNL
            client-secret: e4d8d935aace0b9ddf21111f33cf38462ccaebf9
            scope:
              - user:email
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-security
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: ew0KICAic3ViIjogIjEyMzQ1Njc4OTAiLA0KICAibmFtZSI6ICJBbmlzaCBOYXRoIiwNCiAgImlhdCI6IDE1MTYyMzkwMjINCn0LJrMHYdWlnXnG7cUeHAXrFpg
  expiration: 3600000
  refresh-expiration: 604800000

logging:
  level:
    org:
      springframework:
        security: DEBUG
