spring:
  application:
    name: auth
  security:
    user:
      name: root
      password: root
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-security
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: adapter
    expiration: 3600000
    refresh-expiration: 604800000